### ISSUE TITLE
IDEA: Reusable log messages

### ISSUE THREAD

**Issue by ludeeus** [hassio-addons/bashio#1]
Instead of having logs in every addon, some of the more generic log messages can be handled with this package.
like:

- `bashio.logs.missing_username`
- `bashio.logs.missing_password`
- `bashio.logs.missing_certificate`
- `bashio.logs.missing_file(file)` 
- `bashio.logs.missing_dir(dir)`

Probably some others as well but it is a start.
By doing this it will be a single point for updates and it will ensure constancy in all add-ons.

**Comment by frenck** [comment]
I like this a lot!

Some things to consider:
- The severity of the log message?
- Die?

Some other suggestions:
- `bashio.logs.missing_option` (more generic)
- `bashio.logs.pwned_password`
- `bashio.logs.starting_service(servicename)`

**Comment by frenck** [comment]
not stale

**Comment by frenck** [comment]
This has been added to the library.
