### ISSUE TITLE
"Slug" not sufficient for functions in addons.sh

### ISSUE THREAD

**Issue by brenner-tobias** [hassio-addons/bashio#101]
# Problem/Motivation

I tried getting the IP of the running Nginxproxymanager add-on. So I tried to use `bashio::addon.ip_address`. From the description, I got that the Slug of the add-on was needed, which I provided.

## Expected behavior

When running bashio::addon.ip_address with the Slug of an add-on, it should return the IP-address.

## Actual behavior

It is not sufficient to use the slug, you have to use `core-slug` for Core add-ons and `GithubHash-Slug` for any other add-ons. I am working with this which seems to work fine:

```
npm_name="$(grep nginxproxymanager <<< "$(bashio::addons.installed)")"
npm_ip="$(bashio::addon.ip_address "$npm_name")"
```

## Steps to reproduce

run `bashio::addon.ip_address "nginxproxymanager"` on a system that has Nginx Proxy Manager up and running.

## Proposed changes

From my point of view there are two ways to go here:

1. Leave the logic as it is and just highlight the behaviour in the comments in the code and also potentially add a helper method with a bit nicer version then what I am doing.
2. Strictly work with the slug and not with the Hash-Slug everywhere. This has some implications beyond this library since I guess this is used so multiple add-ons with the same slug but different versions / repositories can be used. Therefor, this would be a big change on the data-structure of add-ons, the API, ..., and also limit the system to one add-on with any given slug. Not really called for here I guess, but I wanted to mention it anyways.

**Comment by frenck** [comment]
> run bashio::addon.ip_address "nginxproxymanager" on a system that has Nginx Proxy Manager up and running.


`nginxproxymanager` isn't a valid/full add-on slug. The repository hash is part of the add-on slug from the supervisor's API perspective.

**Comment by brenner-tobias** [comment]
Thanks a lot for your quick reply. I think this is exactly the point you are raising with "from the supervisor's API perspective."
I still think that it is misleading that the word "Slug" is used in the configuration of every add-on (e.g. "Nginxproxymanager") but at another point it is used as the "valid/full" Slug from the Supervisor's perspective (incl. the repo hash) .
Even if nothing in the logic is changed, making this clear in the comments somewhere would certainly help anyone using this library.

**Comment by frenck** [comment]
Slug in your add-on repository only needs to be unique for your repository.

From the complete eco system perspective you are communicating with, there might be more than 1 `nginxproxymanager`s. As a matter of fact, I have 3 already... which one of the tree are you calling?

> Even if nothing in the logic is changed, making this clear in the comments somewhere would certainly help anyone using this library.

The Supervisor API is documented on the Home Assistant developers' website 👍
