### ISSUE TITLE
bashio::services.wait_for

### ISSUE THREAD

**Issue by marciogranzotto** [hassio-addons/bashio#103]
# Problem/Motivation

I'm trying to create an add-on that has a service that needs to run after another service runs.
I would like to use something like `bashio::net.wait_for` but instead of waiting for a port, wait for a service to run

## Proposed changes

create a `bashio::services.wait_for` function

**Comment by frenck** [comment]
A service provided by the Supervisor always has a port open in some way?
I'm not sure if I follow. Could you provide an example?
