### ISSUE TITLE
[FR] HA Proxy API addition

### ISSUE THREAD

**Issue by patman15** [hassio-addons/bashio#113]
# Problem/Motivation

add support for Home Assistant API via Supervisor Proxy, as discussed in https://github.com/hassio-addons/bashio/issues/31

## Proposed changes

It was not clear to me from https://github.com/hassio-addons/bashio/issues/31 whether the library's functionality shall be limited to supervisor only or whether it just currently does not support it. If the latter, I'm thinking about adding the necessary functionality via a clone of the function in https://github.com/hassio-addons/bashio/blob/main/lib/api.sh and the ask would be if a PR is of interest.
Currently I'm specifically looking at generating events and persistent notifications.

**Comment by frenck** [comment]
> Currently I'm specifically looking at generating events and persistent notifications.

That is not the goal of this library. This library is for interacting with the Supervisor, not Home Assistant.

> Currently I'm specifically looking at generating events and persistent notifications.

That is a bit the wrong way around, Home Assistant pulls data in, we should not push random data in from the outside. That would be against the general architecture of Home Assistant.

The right way to do such things is to expose an API on your application (e.g., using a WebSocket) and build an integration in Home Assistant to communicate with that. Alternatively, you could use protocols for which this already exists (for example, MQTT).

The suggestion made in this PR is both out of scope and incorrect in architecture for its goal.

../Frenck
