### ISSUE TITLE
bashio::config.true Fails with Dash in Name (Maybe?)

### ISSUE THREAD

**Issue by jak119** [hassio-addons/bashio#131]
# Problem/Motivation

I tried to implement `bashio::config.true` with a config name that contained a dash (e.g., `delete-destination`) and it threw the error in the actual behavior section. If I renamed the config to just a single word (e.g., `delete`), it worked as expected.

## Expected behavior

To execute the `bashio::config.true` function

## Actual behavior

```text
jq: error: destination/0 is not defined at <top-level>, line 1:
if (.delete-destination == null) then            
jq: error: destination/0 is not defined at <top-level>, line 3:
        elif (.delete-destination | type == "string") then                      
jq: error: destination/0 is not defined at <top-level>, line 4:
            .delete-destination // empty                    
jq: error: destination/0 is not defined at <top-level>, line 5:
        elif (.delete-destination | type == "boolean") then                      
jq: error: destination/0 is not defined at <top-level>, line 6:
            .delete-destination // false                    
jq: error: destination/0 is not defined at <top-level>, line 7:
        elif (.delete-destination | type == "array") then                      
jq: error: destination/0 is not defined at <top-level>, line 8:
            if (.delete-destination == []) then                        
jq: error: destination/0 is not defined at <top-level>, line 11:
                .delete-destination[]                        
jq: error: destination/0 is not defined at <top-level>, line 13:
        elif (.delete-destination | type == "object") then                      
jq: error: destination/0 is not defined at <top-level>, line 14:
            if (.delete-destination == {}) then                        
jq: error: destination/0 is not defined at <top-level>, line 17:
                .delete-destination                        
jq: error: destination/0 is not defined at <top-level>, line 20:
            .delete-destination       
```

## Steps to reproduce

1. Add a config named `delete-destination`
2. In the bash script executing the container:
    
    ```bash
    $(bashio::config.true 'delete-destination')
    ```

3. Set config in Home Assistant to `true` (although if it's `false` it seems to also error out)
4. Run the container and observe error

### Full example

You can see a full example of this issue in [my repo on this commit](https://github.com/jak119/hassio-backup-azure-blob/tree/b7a4d4aef65a3b4f7aa135da7b8102c0eb8a94ca/azcopy) and the changes I implemented to resolve the error on [this commit](https://github.com/jak119/hassio-backup-azure-blob/commit/a5a5901c98cdf4a13662b073f745e0cc5b4cbc6f)

### Workaround

Use a config without a dash

### Proposed Solution

Handle dashes or document that dashes are not supported either on the Add-On Developer documentation if they're not supported in add-ons or in this repo.

**Comment by sinclairpaul** [comment]
But you aren't typing a dash, it's a minus character which is a subtraction in JSON.

You could look to use en dash characters, but may end up with parsing issues, I would suggest just using an underscore as is done in the Community addons.  

This repo isn't related to the Add-On Developer documentation so there really isn't anything to be done here (It's also in  my view JSON documentation, not specific to anything in HA).
