### ISSUE TITLE
Showing HomeAssistant as taildrop device after disabling taildrop.

### ISSUE THREAD

**Issue by alyyousuf7** [hassio-addons/bashio#159]
# Problem/Motivation

I want to disable `taildrop` for my HomeAssistant - however, disabling it still shows the homeassistant in the taildrop device list in the tailnet.

<img width="1058" alt="image" src="https://github.com/user-attachments/assets/d5360f44-914a-4779-8e3d-2dbec553d312">

![image](https://github.com/user-attachments/assets/1e1281e3-a9bc-4a01-ac4c-42077af8f988)

## Expected behavior

I turned off the Taildrop explicitly (thru UI, and also confirmed with .yaml) - it must not show the device in tailscale for taildrop.

## Actual behavior

The device is shown as a device that can receive taildrop.

## Steps to reproduce

In your config, turn off `taildrop` and restart the addon.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
I'm not entirely sure what that has to do with this repository?

../Frenck

**Comment by alyyousuf7** [comment]
I'm sorry, I thought that this config in this addon would stop taildrop in tailscale completely.

I just learnt that tailscale always exposes devices as taildrop and there's no way to "disable" taildrop - we can only ignore the file.

Closing this issue.
