### ISSUE TITLE
api.supervisor() does not work with Home Assistant REST API

### ISSUE THREAD

**Issue by thomasmauerer** [hassio-addons/bashio#31]
# Problem/Motivation

According to the docs, the supervisor acts as a proxy to the Home Assistant REST API using "core/api". But the bashio function api.supervisor does not work in this case as the REST API behaves different.

## Expected behavior

Get a result from the API.

## Actual behavior

The response is empty, because there is a filter for ".data" which does not exist in this case:

```
[14:18:00] DEBUG: Requested API resource: http://supervisor/core/api/
[14:18:00] DEBUG: Request method: GET
[14:18:00] DEBUG: Request data: {}
[14:18:00] DEBUG: API HTTP Response code: 200
[14:18:00] DEBUG: API Response: {"message": "API running."}
```

Apart from that, all response codes except 200 result in an error. 201 is also a valid response code (e.g. when posting a new state which did not exist before).

## Steps to reproduce

```
result=$(bashio::api.supervisor GET "/core/api/")
echo "$result"
```

## Proposed changes

- return __BASHIO_EXIT_OK on http code 201
- do not filter on .data when call was against the Home Assistant REST API

**Comment by frenck** [comment]
This is correct, Bashio is for interacting with the Supervisor, not Home Assistant Core.

**Comment by thomasmauerer** [comment]
From my understanding I am technically interacting with the supervisor (a proxy in this case) and the call itself works as expected. The thing is just, that the response looks different.

**Comment by frenck** [comment]
Yes, because this library is not designed for interacting with the Home Assistant Core, but is built to interact with the Home Assistant Supervisor API.
