### ISSUE TITLE
bashio::config "parse error: Invalid numeric literal at line 2, column 0"

### ISSUE THREAD

**Issue by ciotlosm** [hassio-addons/bashio#35]
# Problem/Motivation

bashio::config 'my_key' fails when no options file is present with cryptic message

## Expected behavior

A better error specifying that the input file for jq is not there

## Actual behavior

```
parse error: Invalid numeric literal at line 2, column 0
```

## Steps to reproduce

Run locally a built container with bashio to test out startup script messages

## Proposed changes

I think somewhere in https://github.com/hassio-addons/bashio/blob/master/lib/jq.sh#L23 there should be extra validation.

**Comment by frenck** [comment]
The options file is always present in the add-on run environment. Add-ons are not meant to be run outside of the supervisor scope.

**Comment by ciotlosm** [comment]
According to https://developers.home-assistant.io/docs/add-ons/testing#local-run you should be able to test it outside of the environment. Would have been useful for new add-on creators to have an easier time.

**Comment by frenck** [comment]
Feel free to raise an issue @ the Home Assistant project. The community add-ons, including Bashio never took that approach and never will.
