### ISSUE TITLE
bashio::addons.installed not return installed addons

### ISSUE THREAD

**Issue by LiJu09** [hassio-addons/bashio#39]
# Problem/Motivation

`bashio::addons.installed` return all addons available in the store

## Expected behavior

`bashio::addons.installed` return only installed addons

## Steps to reproduce

```
#!/usr/bin/env bashio
echo $(bashio::addons.installed)
```

**Comment by ludeeus** [comment]
Use <https://github.com/hassio-addons/bashio/blob/master/lib/supervisor.sh#L288-L294> of only installed

**Comment by LiJu09** [comment]
But then why this https://github.com/hassio-addons/bashio/blob/3765aa9bf019d2155b46fb8a33dcf1cc35a75b4a/lib/addons.sh#L190 says "Returns a list of installed add-ons"?

**Comment by frenck** [comment]
I cannot reproduce this issue.

![image](https://user-images.githubusercontent.com/195327/104779057-b2ab5200-577e-11eb-8ae8-db18e619e787.png)

**Comment by LiJu09** [comment]
What's wrong?
I don't have installed all these addons.

![screen](https://user-images.githubusercontent.com/40698774/104780078-8690d080-5780-11eb-800b-18e615032f08.png)

**Comment by LiJu09** [comment]
But this works.

![screen1](https://user-images.githubusercontent.com/40698774/104780881-c7d5b000-5781-11eb-83bd-6cfe8ebb3a70.png)
