### ISSUE TITLE
bashio::config does not work for options that contain dashes

### ISSUE THREAD

**Issue by pschmitt** [hassio-addons/bashio#69]
# Problem/Motivation

While working on a [Tailscale addon](https://github.com/pschmitt/home-assistant-addons/tree/master/tailscale) I noticed that `bashio::config` is not able to parse JSON options files that contain hyphens. 

## Expected behavior

`bashio::config` should be able to handle any kind of valid JSON, even when keys contain dashes.

## Actual behavior

Right now only keys without dashes are supported.

## Steps to reproduce

Here's a sample `options.json` that currently cannot be parsed:

```json
{"this-is-a-test": true}
```

## Proposed changes

Since `bashio::config` is using `jq` behind the scenes it would make sense to use the `["item-with-dashes"]` or the `."item-with-dashes"` notation instead of `.item-with-dashes`

- https://github.com/stedolan/jq/issues/38
- https://stackoverflow.com/questions/37344329/jq-not-working-on-tag-name-with-dashes-and-numbers

**Comment by frenck** [comment]
😓 I didn't even know that was valid, to be honest.

**Comment by pschmitt** [comment]
Not stale AFAIK.

**Comment by pschmitt** [comment]
Nyet.

**Comment by MatteoGheza** [comment]
.
