### ISSUE TITLE
Bashio logging mysql password in debug mode

### ISSUE THREAD

**Issue by mdegat01** [hassio-addons/bashio#73]
# Problem/Motivation

I turned on debug logging on the Nginx Proxy Manager addon and noticed it was dumping out the login credentials of the service operator for the mariadb addon. It looks like `bashio::api.supervisor` dumps out the raw response every time when in debug mode. I don't think we should be logging passwords at any point, especially not for the service operator like this.

<img width="1003" alt="Screen Shot 2021-04-01 at 9 34 55 PM" src="https://user-images.githubusercontent.com/2037026/113371237-e0427900-9333-11eb-881d-075699ff43a5.png">

## Expected behavior

Credentials shouldn't be logged

## Actual behavior

Service operator credentials were logged when in debug mode for an addon using the `mysql` service.

## Steps to reproduce

1. Install an addon that uses the `mysql` service (Nginx Proxy Manager for example)
2. Set log level to `debug`
3. Start the addon and check the logs

## Proposed changes

Few ideas:
1) Add a parameter to `bashio::api.supervisor` to not log the response and provide it from `bashio::services`
2) Don't log responses from `bashio::api.supervisor` for APIs known to contain passwords (like `/services`)
3) Run a filter on the response before logging it to look for common patterns (like a field called `password`) and obfuscate if found

**Comment by frenck** [comment]
It only logs in debug mode.
